name: Auto Create PR
on:
  push:
    branches-ignore: [main, master] # Skip default branch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto PR for ${{ github.ref }}"
          branch: ${{ github.ref }}
          base: main # Your default branch
          body: "Automatically created PR"
